import 'package:flutter/material.dart';
import 'package:ikelapp/constant.dart';
import 'package:ikelapp/screens/client/product_page.dart';

// ignore: must_be_immutable
class HardDrinks extends StatelessWidget {
  ProductPage productpage = ProductPage();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFFFCFAF8),
      body: ListView(
        children: <Widget>[
          SizedBox(height: 15.0),
          Container(
              padding: EdgeInsets.only(right: 15.0),
              width: MediaQuery.of(context).size.width - 30.0,
              height: MediaQuery.of(context).size.height - 50.0,
              child: GridView.count(
                crossAxisCount: 2,
                primary: false,
                crossAxisSpacing: 10.0,
                mainAxisSpacing: 15.0,
                childAspectRatio: 0.8,
                children: <Widget>[
                  productpage.build(
                      '100 años 700 ml',
                      '\$140.00',
                      'assets/imgs/HardDrink/100anosreposado.png',
                      false,
                      false,
                      "Detalle 100 años",
                      context),
                  productpage.build(
                      '400 Conejos 750ml',
                      '\$435.00',
                      'assets/imgs/HardDrink/400conejos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      '1800 Cristalino 700ml',
                      '\$635.00',
                      'assets/imgs/HardDrink/1800cristalino.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Absinth 700ml',
                      '\$555.00',
                      'assets/imgs/HardDrink/Absinth.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Absolut Azul 750 ml',
                      '\$259.00',
                      'assets/imgs/HardDrink/AbsolutAzul.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Absolut Mandarina 750 ml',
                      '\$259.00',
                      'assets/imgs/HardDrink/AbsolutMandrin.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Alacrán Jóven 750 ml ',
                      '\$639.00',
                      'assets/imgs/HardDrink/AlacranJoven.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Alipús San Juan del Río 750ml',
                      '\$717.00',
                      'assets/imgs/HardDrink/AlipusSanJuandelRio.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Appleton Estate 750ml',
                      '\$250.00',
                      'assets/imgs/HardDrink/AppletonEstate.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Appleton Special 750ml',
                      '\$635.00',
                      'assets/imgs/HardDrink/AppletonSpecial.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Azteca de Oro 700 ml',
                      '\$150.00',
                      'assets/imgs/HardDrink/AztecadeOro.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Bacardí Blanco 750ml',
                      '\$165.00',
                      'assets/imgs/HardDrink/BacardiBlanco.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Bacardí Blanco 980 ml',
                      '\$210.00',
                      'assets/imgs/HardDrink/BacardiBlanco980ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Bacardí Blanco 1750ml',
                      '\$310.00',
                      'assets/imgs/HardDrink/BacardiBlanco1750.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Bacardi Solera 750ml',
                      '\$220.00',
                      'assets/imgs/HardDrink/BacardiSolera.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Baileys Original 700ml',
                      '\$315.00',
                      'assets/imgs/HardDrink/BaileysOriginal.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Beefeater 750ml',
                      '\$412.00',
                      'assets/imgs/HardDrink/Beefeater.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Beringer White Zinfandel 750ml',
                      '\$201.00',
                      'assets/imgs/HardDrink/BeringerWhiteZinfandel.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Black & White 700ml',
                      '\$200.00',
                      'assets/imgs/HardDrink/BlackWhite.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Bombay Sapphire 750ml',
                      '\$475.00',
                      'assets/imgs/HardDrink/Bombay.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Bruxo No.1 750ml',
                      '\$515.00',
                      'assets/imgs/HardDrink/Bruxo.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Buchanans 12 años 750ml',
                      '\$780.00',
                      'assets/imgs/HardDrink/Buchanans12anos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Buchanan´s 18 años 750ml',
                      '\$780.00',
                      'assets/imgs/HardDrink/Buchanans18anos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Buchanan´s Master 750ml',
                      '\$895.00',
                      'assets/imgs/HardDrink/BuchanansMaster.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Bulldog 750ml',
                      '\$550.00',
                      'assets/imgs/HardDrink/Bulldog.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Captain Morgan Spiced 750ml',
                      '\$149.00',
                      'assets/imgs/HardDrink/CaptainMorganSpiced750ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Cardenal de Mendoza 700ml',
                      '\$1063.00',
                      'assets/imgs/HardDrink/Cardenaldeendoza.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Cazadores Reposado 950ml',
                      '\$230.00',
                      'assets/imgs/HardDrink/CazadoresReposado.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Centenario Plata 700 ml',
                      '\$305.00',
                      'assets/imgs/HardDrink/CentenarioPlata700ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Centenario Plata 950 ml',
                      '\$317.00',
                      'assets/imgs/HardDrink/CentenarioPlata950ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Centenario Reposado 950ml',
                      '\$255.00',
                      'assets/imgs/HardDrink/centenarioreposado.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Chilensis Reserva 750ml',
                      '\$180.00',
                      'assets/imgs/HardDrink/ChilensisReserva.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Chivas Regal 12 años 750ml',
                      '\$695.00',
                      'assets/imgs/HardDrink/ChivasRegal12anos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Courvoisier V.S. 700ml',
                      '\$625.00',
                      'assets/imgs/HardDrink/COURVOISIERVS.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Cune de Rioja Semidulce 750ml',
                      '\$200.00',
                      'assets/imgs/HardDrink/CuneRiojaSemidulce.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Don julio 70 700ml',
                      '\$570.00',
                      'assets/imgs/HardDrink/Donjulio70.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Don Julio Reposado 700ml',
                      '\$835.00',
                      'assets/imgs/HardDrink/DonJulioReposado.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Don Pedro 750ml',
                      '\$160.00',
                      'assets/imgs/HardDrink/DonPedro.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'El Jimador reposado 700ml',
                      '\$195.00',
                      'assets/imgs/HardDrink/ElJimadorreposado.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Finca las Moras Malbec 750ml',
                      '\$142.00',
                      'assets/imgs/HardDrink/FincalasMorasMalbec.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Frangelico 700ml',
                      '\$350.00',
                      'assets/imgs/HardDrink/Frangelico.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Fundador 700ml',
                      '\$185.00',
                      'assets/imgs/HardDrink/Fundador.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Glenfiddich 12 años 750ml',
                      '\$915.00',
                      'assets/imgs/HardDrink/Glenfiddich12anos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Grey Goose 750ml',
                      '\$660.00',
                      'assets/imgs/HardDrink/GreyGoose.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Havana Club 750 ml',
                      '\$442.00',
                      'assets/imgs/HardDrink/HavanaClub750ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Hendricks',
                      '\$750.00',
                      'assets/imgs/HardDrink/Hendricks.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Hennessy V.S.O.P 700ml',
                      '\$1080.00',
                      'assets/imgs/HardDrink/HennessyVSOP.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Herradura Reposado 700ml',
                      '\$549.00',
                      'assets/imgs/HardDrink/HerraduraReposado700.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Hornitos Reposado 700ml',
                      '\$275.00',
                      'assets/imgs/HardDrink/HornitosReposado700.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Hpnotiq 750ml',
                      '\$650.00',
                      'assets/imgs/HardDrink/Hpnotiq.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Jack Daniels 700ml',
                      '\$415.00',
                      'assets/imgs/HardDrink/JackDaniels.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Jagermeister 700ml',
                      '\$320.00',
                      'assets/imgs/HardDrink/Jagermeifter.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Jameson 750ml',
                      '\$371.00',
                      'assets/imgs/HardDrink/Jameson.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'J & B 750ml',
                      '\$240.00',
                      'assets/imgs/HardDrink/JB.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Johnnie Walker Etiqueta Negra 750ml',
                      '\$830.00',
                      'assets/imgs/HardDrink/JohnnieWalkerEtiquetaNegra.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Johnnie Walker Etiqueta Roja 700ml',
                      '\$325.00',
                      'assets/imgs/HardDrink/JohnnieWalkerEtiquetaRoja.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Jose Cuervo Especial 990ml',
                      '\$205.00',
                      'assets/imgs/HardDrink/JoseCuervoEspecial.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Jose Cuervo tradicional 950ml',
                      '\$330.00',
                      'assets/imgs/HardDrink/JoseCuervotradicional.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Kahlúa 1L',
                      '\$166.00',
                      'assets/imgs/HardDrink/KahluaLicordeCafe.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Karat 1L',
                      '\$130.00',
                      'assets/imgs/HardDrink/Karat1lt.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Kraken Black Spiced 750ml',
                      '\$165.00',
                      'assets/imgs/HardDrink/KrakenBlackSpiced.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'L.A. Cetto Cabernet Sauvignon 750ml',
                      '\$136.00',
                      'assets/imgs/HardDrink/LACetto.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'L.A. Cetto Blanc Zinfandel 750ml',
                      '\$131.00',
                      'assets/imgs/HardDrink/LACettoBlancdeZinfandel.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Licor 43 700ml',
                      '\$430.00',
                      'assets/imgs/HardDrink/Licor43.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Macallan Double Cask 700ml',
                      '\$1260.00',
                      'assets/imgs/HardDrink/MacallanDobleCask.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Maestro Dobel Diamante 700ml',
                      '\$650.00',
                      'assets/imgs/HardDrink/MaestroDobel.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Malibu 750ml',
                      '\$187.00',
                      'assets/imgs/HardDrink/Malibu.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Martell V.S. 700ml',
                      '\$700.00',
                      'assets/imgs/HardDrink/Martellvs.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Martell V.S.O.P 700ml',
                      '\$949.00',
                      'assets/imgs/HardDrink/MartellVSOP.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Matusalem Clásico 750ml',
                      '\$224.00',
                      'assets/imgs/HardDrink/MatusalemClasico.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Matusalem Platino 750ml',
                      '\$190.00',
                      'assets/imgs/HardDrink/MatusalemPlatino.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  // productpage.build(
                  //     'Mezcal Union Uno',
                  //     '\$N/A.00',
                  //     'assets/imgs/HardDrink/MezcalUnionUno.png',
                  //     false,
                  //     false,
                  //     "Detalle producto",
                  //     context),
                  productpage.build(
                      'Midori 750ml',
                      '\$405.00',
                      'assets/imgs/HardDrink/Midori.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Moet Chandón Brut 750ml',
                      '\$1050.00',
                      'assets/imgs/HardDrink/MoetChandonBrut.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Moet Chandón Ice Imperial 750ml',
                      '\$1655.00',
                      'assets/imgs/HardDrink/MoetChandonIceImperial.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Moet Chandón Rose 750ml',
                      '\$1295.00',
                      'assets/imgs/HardDrink/MoetChandonRose.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Monte Xanic Merlot 750ml',
                      '\$545.00',
                      'assets/imgs/HardDrink/MonteXanicMerlot.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Nuvo 700ml',
                      '\$770.00',
                      'assets/imgs/HardDrink/Nuvo.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Oso Negro Ginebra 1L',
                      '\$120.00',
                      'assets/imgs/HardDrink/OsoNegroGinebra.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Oso Ngero Vodka 1L',
                      '\$90.00',
                      'assets/imgs/HardDrink/OsoNgero1lt.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Passport Scotch 700ml',
                      '\$160.00',
                      'assets/imgs/HardDrink/PassportScotch.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Remy Martin 1738 700ml',
                      '\$1420.00',
                      'assets/imgs/HardDrink/RemyMartin1738.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Remy Martin V.S.O.P. 700ml',
                      '\$1100.00',
                      'assets/imgs/HardDrink/RemyMartinVSOP.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Riunite Lambrusco 750ml',
                      '\$140.00',
                      'assets/imgs/HardDrink/RiuniteLambrusco.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Riunite Prosecco 750ml',
                      '\$280.00',
                      'assets/imgs/HardDrink/RiuniteProsecco.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Sauza 700ml',
                      '\$229.00',
                      'assets/imgs/HardDrink/Sauza.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Skyy Vodka 750ml',
                      '\$165.00',
                      'assets/imgs/HardDrink/SkyyVodka.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Smirnoff 750 ml',
                      '\$185.00',
                      'assets/imgs/HardDrink/Smirnoff750ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Smirnoff Tamarindo 750ml',
                      '\$200.00',
                      'assets/imgs/HardDrink/SmirnoffTamarindo.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Stolichnaya 750ml',
                      '\$265.00',
                      'assets/imgs/HardDrink/Stolichnaya.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Tanqueray 750ml',
                      '\$455.00',
                      'assets/imgs/HardDrink/Tanqueray.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Terry Centenario 700ml',
                      '\$280.00',
                      'assets/imgs/HardDrink/TerryCentenario.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Torres 10 700ml',
                      '\$290.00',
                      'assets/imgs/HardDrink/Torres10.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Torres 15 700ml',
                      '\$510.00',
                      'assets/imgs/HardDrink/Torres15.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Torres 20 700ml',
                      '\$875.00',
                      'assets/imgs/HardDrink/Torres20.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Wyborowa 750ml',
                      '\$139.00',
                      'assets/imgs/HardDrink/Wyborowa.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'XA DOMECQ 750ml',
                      '\$120.00',
                      'assets/imgs/HardDrink/XADOMECQ.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  productpage.build(
                      'Zacapa 23 750ml',
                      '\$1100.00',
                      'assets/imgs/HardDrink/Zacapa23.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                ],
              )),
          SizedBox(height: 15.0)
        ],
      ),
    );
  }
}
