name: ikelapp
description: Aplicacion para venta de bebidas .
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  counter_button: ^1.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geolocator: ^8.0.5
  google_maps_flutter: ^2.1.2
  http: ^0.13.3
  image_picker: ^0.7.5+4
  location: ^4.4.0
  map_launcher: ^2.4.0
  maps_launcher: ^2.0.1
  permission_handler: ^9.0.1
  shared_preferences: ^2.0.6
  url_launcher: ^6.1.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  carousel_slider: ^4.2.1
  flutter_svg: ^1.1.6
dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/imgs/PistosMix/
    - assets/imgs/Healthyfun/
    - assets/imgs/HardDrink/
    - assets/imgs/Candysparty/
    - assets/imgs/Beerhouse/
