import 'package:flutter/material.dart';
import 'package:blogapp/screens/product_detail.dart';

import '../constant.dart';

class BeerHouse extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFFFCFAF8),
      body: ListView(
        children: <Widget>[
          SizedBox(height: 15.0),
          Container(
              padding: EdgeInsets.only(right: 15.0),
              width: MediaQuery.of(context).size.width - 30.0,
              height: MediaQuery.of(context).size.height - 50.0,
              child: GridView.count(
                crossAxisCount: 2,
                primary: false,
                crossAxisSpacing: 10.0,
                mainAxisSpacing: 15.0,
                childAspectRatio: 0.8,
                children: <Widget>[
                  _buildCard(
                      'Barrilito 355 ml',
                      '\$11.00',
                      'imgs/Beerhouse/Barrilito355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Barrilito 444ml',
                      '\$13.00',
                      'imgs/Beerhouse/Barrilito444ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Bocanegra 355ml',
                      '\$28.00',
                      'imgs/Beerhouse/Bocanegra355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Bohemia Clara 355 ml',
                      '\$13.00',
                      'imgs/Beerhouse/BohemiaClara355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Bohemia Clara No retornable 355',
                      '\$16.00',
                      'imgs/Beerhouse/BohemiaClaraNoretornable355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Bohemia Obscura 355',
                      '\$13.00',
                      'imgs/Beerhouse/BohemiaObscura355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Bohemia Obscura No retornable 355',
                      '\$16.00',
                      'imgs/Beerhouse/BohemiaObscuraNoretornable355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Brooklyn 355ml',
                      '\$44.00',
                      'imgs/Beerhouse/Brooklyn355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'BudLight 355ml',
                      '\$14.00',
                      'imgs/Beerhouse/BudLight355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Carta Blanca 355',
                      '\$16.00',
                      'imgs/Beerhouse/CartaBlanca355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Carta Blanca 940ml',
                      '\$24.00',
                      'imgs/Beerhouse/CartaBlanca940ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Carta Blanca No retornable 355',
                      '\$16.00',
                      'imgs/Beerhouse/CartaBlancaNoretornable355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cornona 355ml',
                      '\$14.00',
                      'imgs/Beerhouse/Cornona355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Corona 1.2L',
                      '\$34.00',
                      'imgs/Beerhouse/Corona12L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Corona 940ml',
                      '\$30.00',
                      'imgs/Beerhouse/Corona940ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Corona Ampolleta',
                      '\$10.00',
                      'imgs/Beerhouse/CoronaAmpolleta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Corona Light 1.2L',
                      '\$34.00',
                      'imgs/Beerhouse/CoronaLight12L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Corona Light 355ml',
                      '\$14.00',
                      'imgs/Beerhouse/CoronaLight355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Goose Island 355ml',
                      '\$49.00',
                      'imgs/Beerhouse/GooseIsland355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Gran Modelo 1L',
                      '\$35.00',
                      'imgs/Beerhouse/GranModelo1L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Grimbergen 330ml',
                      '\$32.00',
                      'imgs/Beerhouse/Grimbergen330ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Heineken 1L',
                      '\$33.00',
                      'imgs/Beerhouse/Heineken1L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Heineken 250 ml',
                      '\$12.00',
                      'imgs/Beerhouse/Heineken250ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Heineken 355 ml',
                      '\$17.00',
                      'imgs/Beerhouse/Heineken355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Heineken No Retornable 355 ml',
                      '\$17.00',
                      'imgs/Beerhouse/HeinekenNoRetornable355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Hoegaarden 355ml',
                      '\$29.00',
                      'imgs/Beerhouse/Hoegaarden355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Indio 1.18L',
                      '\$31.00',
                      'imgs/Beerhouse/Indio118L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Indio 355ml',
                      '\$13.00',
                      'imgs/Beerhouse/Indio355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Indio 940ml',
                      '\$25.00',
                      'imgs/Beerhouse/Indio940ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Indio ampolleta',
                      '\$7.00',
                      'imgs/Beerhouse/Indioampolleta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Indio No Retornable 355ml',
                      '\$13.00',
                      'imgs/Beerhouse/IndioNoRetornable355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'JabalI 330ml',
                      '\$33.00',
                      'imgs/Beerhouse/JabalI330ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Lagunitas Ipa 355ml',
                      '\$31.00',
                      'imgs/Beerhouse/LagunitasIpa355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Leon 1.2L',
                      '\$34.00',
                      'imgs/Beerhouse/Leon12L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Leon 355ml',
                      '\$14.00',
                      'imgs/Beerhouse/Leon355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Leon No retornable 325',
                      '\$14.00',
                      'imgs/Beerhouse/LeonNoretornable325.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Michelob Ultra 355ml',
                      '\$17.00',
                      'imgs/Beerhouse/MichelobUltra355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Modelo Ambar 355ml',
                      '\$16.00',
                      'imgs/Beerhouse/ModeloAmbar355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Modelo Especial 355ml',
                      '\$16.00',
                      'imgs/Beerhouse/ModeloEspecial355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Modelo Trigo 355ml',
                      '\$16.00',
                      'imgs/Beerhouse/ModeloTrigo355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Montejo 355ml',
                      '\$16.00',
                      'imgs/Beerhouse/Montejo355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Negra Modelo 355ml',
                      '\$16.00',
                      'imgs/Beerhouse/NegraModelo355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Noche Buena 355ml',
                      '\$15.00',
                      'imgs/Beerhouse/NocheBuena355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Pacifico 355',
                      '\$14.00',
                      'imgs/Beerhouse/Pacifico355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Pacifico Ampolleta',
                      '\$10.00',
                      'imgs/Beerhouse/PacificoAmpolleta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Pacifico Light Ampolleta',
                      '\$10.00',
                      'imgs/Beerhouse/PacificoLightAmpolleta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Quilmes 355ml',
                      '\$25.00',
                      'imgs/Beerhouse/Quilmes355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard('Sol 355', '\$13.00', 'imgs/Beerhouse/Sol355.png',
                      false, false, "Detalle de Producto", context),
                  _buildCard(
                      'Sol 940ml',
                      '\$25.00',
                      'imgs/Beerhouse/Sol940ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Sol Ampolleta',
                      '\$7.00',
                      'imgs/Beerhouse/SolAmpolleta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Sol No retornable 355ml',
                      '\$13.00',
                      'imgs/Beerhouse/SolNoretornable355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Stella Artois 310ml',
                      '\$19.00',
                      'imgs/Beerhouse/StellaArtois310ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Superior 355ml',
                      '\$13.00',
                      'imgs/Beerhouse/Superior355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tecate Ambar 355ml',
                      '\$10.00',
                      'imgs/Beerhouse/TecateAmbar355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tecate Ambar 940ml',
                      '\$25.00',
                      'imgs/Beerhouse/TecateAmbar940ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tecate Light 1.18L',
                      '\$31.00',
                      'imgs/Beerhouse/TecateLight118L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tecate Light 355ml',
                      '\$13.00',
                      'imgs/Beerhouse/TecateLight355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tecate Light No Retornable 355ml',
                      '\$10.00',
                      'imgs/Beerhouse/TecateLightNoRetornable355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tecate Roja 1.18L',
                      '\$31.00',
                      'imgs/Beerhouse/TecateRoja118L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tecate Roja 355ml',
                      '\$10.00',
                      'imgs/Beerhouse/TecateRoja355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tempus 355ml',
                      '\$30.00',
                      'imgs/Beerhouse/Tempus355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tuborg 330ml',
                      '\$16.00',
                      'imgs/Beerhouse/Tuborg330ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Victoria 1.2L',
                      '\$34.00',
                      'imgs/Beerhouse/Victoria12L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Victoria 355ml',
                      '\$14.00',
                      'imgs/Beerhouse/Victoria355ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Victoria 940ml',
                      '\$30.00',
                      'imgs/Beerhouse/Victoria940ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Victoria Ampolleta',
                      '\$10.00',
                      'imgs/Beerhouse/VictoriaAmpolleta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'XX Lager 1.18L',
                      '\$34.00',
                      'imgs/Beerhouse/XXLager118L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'XX Lager 355ml',
                      '\$11.00',
                      'imgs/Beerhouse/XXLager355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'XX Lager Ambar 1.18L',
                      '\$34.00',
                      'imgs/Beerhouse/XXLagerAmbar118L.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'XX Lager Ambar 355',
                      '\$11.00',
                      'imgs/Beerhouse/XXLagerAmbar355.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'XX lager Ampolleta',
                      '\$8.00',
                      'imgs/Beerhouse/XXlagerAmpolleta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                ],
              )),
          SizedBox(height: 15.0)
        ],
      ),
    );
  }

  Widget _buildCard(String name, String price, String imgPath, bool added,
      bool isFavorite, String detalle, context) {
    return Padding(
        padding: EdgeInsets.only(top: 5.0, bottom: 5.0, left: 5.0, right: 5.0),
        child: InkWell(
            onTap: () {
              Navigator.of(context).push(MaterialPageRoute(
                  builder: (context) => ProductDetail(
                        assetPath: imgPath,
                        cookieprice: price,
                        cookiename: name,
                        detalle: detalle,
                      )));
            },
            child: Container(
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15.0),
                    boxShadow: [
                      BoxShadow(
                          color: Colors.grey.withOpacity(0.2),
                          spreadRadius: 3.0,
                          blurRadius: 5.0)
                    ],
                    color: Colors.white),
                child: Column(children: [
                  Padding(
                      padding: EdgeInsets.all(5.0),
                      child: Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            isFavorite
                                ? Icon(Icons.favorite, color: Color(0xFFEF7532))
                                : Icon(Icons.favorite_border,
                                    color: Color(0xFFEF7532))
                          ])),
                  Hero(
                      tag: imgPath,
                      child: Container(
                          height: 110,
                          width: 110,
                          decoration: BoxDecoration(
                              image: DecorationImage(
                                  image: AssetImage(imgPath),
                                  fit: BoxFit.contain)))),
                  SizedBox(height: 7.0),
                  Text(price,
                      style: TextStyle(
                          color: PRYMARY_COLOR,
                          fontFamily: 'Varela',
                          fontSize: 14.0)),
                  Text(name,
                      style: TextStyle(
                          color: Color(0xFF575E67),
                          fontFamily: 'Varela',
                          fontSize: 14.0)),
                  Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Container(color: Color(0xFFEBEBEB), height: 1.0)),
                  Padding(
                      padding: EdgeInsets.only(left: 5.0, right: 5.0),
                      child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            if (!added) ...[
                              Icon(Icons.shopping_basket,
                                  color: Color(0xFFD17E50), size: 12.0),
                              Text('Add to cart',
                                  style: TextStyle(
                                      fontFamily: 'Varela',
                                      color: Color(0xFFD17E50),
                                      fontSize: 12.0))
                            ],
                            if (added) ...[
                              Icon(Icons.remove_circle_outline,
                                  color: Color(0xFFD17E50), size: 12.0),
                              Text('3',
                                  style: TextStyle(
                                      fontFamily: 'Varela',
                                      color: Color(0xFFD17E50),
                                      fontWeight: FontWeight.bold,
                                      fontSize: 12.0)),
                              Icon(Icons.add_circle_outline,
                                  color: Color(0xFFD17E50), size: 12.0),
                            ]
                          ]))
                ]))));
  }
}
