import 'package:flutter/material.dart';
import 'package:blogapp/screens/product_detail.dart';

import '../constant.dart';

class CandysParty extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFFFCFAF8),
      body: ListView(
        children: <Widget>[
          SizedBox(height: 15.0),
          Container(
              padding: EdgeInsets.only(right: 15.0),
              width: MediaQuery.of(context).size.width - 30.0,
              height: MediaQuery.of(context).size.height - 50.0,
              child: GridView.count(
                crossAxisCount: 2,
                primary: false,
                crossAxisSpacing: 10.0,
                mainAxisSpacing: 15.0,
                childAspectRatio: 0.8,
                children: <Widget>[
                  _buildCard(
                      'Agua mineral ciel 1.75lts',
                      '\$23.00',
                      'imgs/Candysparty/Aguamineralciel175lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Agua mineral Perrier',
                      '\$29.00',
                      'imgs/Candysparty/AguaMineralPerrier.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Agua Natural 1lt',
                      '\$8.00',
                      'imgs/Candysparty/AguaNatural1lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Agua Natural 500ml',
                      '\$5.00',
                      'imgs/Candysparty/AguaNatural500ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Benson Hedges Gold Cajetilla',
                      '\$63.00',
                      'imgs/Candysparty/BensonHedgesGoldCajetillas.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Benson Hedges Mentolados Cajetilla',
                      '\$63.00',
                      'imgs/Candysparty/BensonHedgesMentolCajetillas.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Bolsa de Hielo',
                      '\$27.00',
                      'imgs/Candysparty/BolsadeHielo.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Boost 235ml',
                      '\$25.00',
                      'imgs/Candysparty/Boost235ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Botana Mixta',
                      '\$29.00',
                      'imgs/Candysparty/BotanaMixta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cacahuate Enchilado',
                      '\$29.00',
                      'imgs/Candysparty/CacahuateEnchilado.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cacahuate Garapiñado 200gr',
                      '\$N/A',
                      'imgs/Candysparty/CacahuateGarapinado200gr.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cacahuate Japones',
                      '\$69',
                      'imgs/Candysparty/CacahuateJapones.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cacahuate japones 160gr',
                      '\$20',
                      'imgs/Candysparty/Cacahuatejapones160gr.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cacahuate Salado sol',
                      '\$69',
                      'imgs/Candysparty/CacahuateSaladosol.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cacahuate surtido 185gr',
                      '\$20',
                      'imgs/Candysparty/Cacahuatesurtido185gr.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cacahuate Tipo Español con Ajo',
                      '\$69',
                      'imgs/Candysparty/CacahuateTipoEspanolconAjo.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Canada Dry 237ml',
                      '\$N/A',
                      'imgs/Candysparty/CanadaDry237ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Candy Camel Cajetilla',
                      '\$63.00',
                      'imgs/Candysparty/candycamelcajetilla.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Charritos chile y limón',
                      '\$15.00',
                      'imgs/Candysparty/Charritoschileylimon.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Clamato 2.5lts',
                      '\$69.00',
                      'imgs/Candysparty/Clamato25lts.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Coca Cola 1lt',
                      '\$20.00',
                      'imgs/Candysparty/CocaCola1lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Coca Cola 2.5lt',
                      '\$36.00',
                      'imgs/Candysparty/CocaCola25lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Coca Cola light 2lt',
                      '\$31.00',
                      'imgs/Candysparty/CocaColalight2lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Crunchi sol Cuadritos',
                      '\$N/A',
                      'imgs/Candysparty/CrunchisolCuadritos.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Crunchisol Donitas Enchiladas',
                      '\$N/A',
                      'imgs/Candysparty/CrunchisolDonitasEnchiladas.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Cueritosde Cerdo 750gr',
                      '\$59.00',
                      'imgs/Candysparty/CueritosdeCerdo750gr.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Fresca 2lt',
                      '\$29.00',
                      'imgs/Candysparty/Fresca2lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'frituras sabor queso sol 300gr',
                      '\$20.00',
                      'imgs/Candysparty/friturassaborquesosol300gr.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Garbanzo Enchilado',
                      '\$69.00',
                      'imgs/Candysparty/GarbanzoEnchilado.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Garbanzo enchilado 140gr',
                      '\$20.00',
                      'imgs/Candysparty/Garbanzoenchilado140gr.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Ginger Ale 237 ml',
                      '\$9.00',
                      'imgs/Candysparty/GingerAle237ml.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Haba Enchilada',
                      '\$69.00',
                      'imgs/Candysparty/HabaEnchilada.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Haba Enchilada 120gr',
                      '\$20.00',
                      'imgs/Candysparty/HabaEnchilada120gr.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Halls Negras',
                      '\$10.00',
                      'imgs/Candysparty/HallsNegras.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Marlboro gold cajetilla',
                      '\$63.00',
                      'imgs/Candysparty/Marlborogoldcajetilla.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Marlboro Ice Xpress',
                      '\$63.00',
                      'imgs/Candysparty/MarlboroIceXpress.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Marlboro Rojo cajetilla',
                      '\$63.00',
                      'imgs/Candysparty/marlboroRojocajetilla.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Maruchan',
                      '\$15.00',
                      'imgs/Candysparty/Maruchan.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Monster Energy',
                      '\$42.00',
                      'imgs/Candysparty/MonsterEnergy.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Mundet Prisco',
                      '\$12.00',
                      'imgs/Candysparty/MundetPrisco.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Nectar del Valle Naranja',
                      '\$19.00',
                      'imgs/Candysparty/NectardelValleNaranja.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Nectar del Valle Uva',
                      '\$19.00',
                      'imgs/Candysparty/NectardelValleUva.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Nectar del Valle Piña',
                      '\$19.00',
                      'imgs/Candysparty/NectarPinaDelValle.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Ocean Spray Cranberry',
                      '\$26.00',
                      'imgs/Candysparty/OceanSprayCranberry.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Ocean Spray Uva',
                      '\$26.00',
                      'imgs/Candysparty/OceanSprayUva.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Papa Adobada sol',
                      '\$59.00',
                      'imgs/Candysparty/PapaAdobadasol.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Papa con queso sol',
                      '\$59.00',
                      'imgs/Candysparty/Papaconquesosol.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Papa Natural de sal',
                      '\$59.00',
                      'imgs/Candysparty/PapaNaturaldelsal.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Peñafiel 1lt',
                      '\$12.00',
                      'imgs/Candysparty/Penafiel1lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Pepita frita',
                      '\$99.00',
                      'imgs/Candysparty/Pepitafrita.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Pepitarusa100gr',
                      '\$20.00',
                      'imgs/Candysparty/Pepitarusa100gr.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'RedBull Energy',
                      '\$40.00',
                      'imgs/Candysparty/RedBullEnergy.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'RedBull Sugar Free',
                      '\$40.00',
                      'imgs/Candysparty/RedBullSugarFree.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'RedBull Tropical',
                      '\$40.00',
                      'imgs/Candysparty/RedBullTropical.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Rockaleta',
                      '\$5.00',
                      'imgs/Candysparty/Rockaleta.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Sal La Fina',
                      '\$15.00',
                      'imgs/Candysparty/SalLaFina.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Salsa Valentina',
                      '\$15.00',
                      'imgs/Candysparty/SalsaValentina.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Sangría Señorial 1lt',
                      '\$21.00',
                      'imgs/Candysparty/SangriaSenorial1lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Sangrita Viuda de Sanchez',
                      '\$71.00',
                      'imgs/Candysparty/SangritaViudadeSanchez.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Sidral Mundet 2lt',
                      '\$29.00',
                      'imgs/Candysparty/SidralMundet2lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Skyy Blue',
                      '\$22.00',
                      'imgs/Candysparty/SkyyBlue.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Sangria Señorial 2lt',
                      '\$30.00',
                      'imgs/Candysparty/SnagriaSenorial2lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Sprite 2lt',
                      '\$29.00',
                      'imgs/Candysparty/Sprite2lt.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Trident XtraCare Menta Tabletas',
                      '\$10.00',
                      'imgs/Candysparty/Trident.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard(
                      'Tubi Charro Naturales',
                      '\$N/A',
                      'imgs/Candysparty/TubiCharroNaturales.png',
                      false,
                      false,
                      "Detalle de Producto",
                      context),
                  _buildCard('Tupsi Pop', '\$5', 'imgs/Candysparty/Tupsi.png',
                      false, false, "Detalle de Producto", context),
                ],
              )),
          SizedBox(height: 15.0)
        ],
      ),
    );
  }

  Widget _buildCard(String name, String price, String imgPath, bool added,
      bool isFavorite, String detalle, context) {
    return Padding(
        padding: EdgeInsets.only(top: 5.0, bottom: 5.0, left: 5.0, right: 5.0),
        child: InkWell(
            onTap: () {
              Navigator.of(context).push(MaterialPageRoute(
                  builder: (context) => ProductDetail(
                        assetPath: imgPath,
                        cookieprice: price,
                        cookiename: name,
                        detalle: detalle,
                      )));
            },
            child: Container(
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15.0),
                    boxShadow: [
                      BoxShadow(
                          color: Colors.grey.withOpacity(0.2),
                          spreadRadius: 3.0,
                          blurRadius: 5.0)
                    ],
                    color: Colors.white),
                child: Column(children: [
                  Padding(
                      padding: EdgeInsets.all(5.0),
                      child: Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            isFavorite
                                ? Icon(Icons.favorite, color: Color(0xFFEF7532))
                                : Icon(Icons.favorite_border,
                                    color: Color(0xFFEF7532))
                          ])),
                  Hero(
                      tag: imgPath,
                      child: Container(
                          height: 110,
                          width: 110,
                          decoration: BoxDecoration(
                              image: DecorationImage(
                                  image: AssetImage(imgPath),
                                  fit: BoxFit.contain)))),
                  SizedBox(height: 7.0),
                  Text(price,
                      style: TextStyle(
                          color: PRYMARY_COLOR,
                          fontFamily: 'Varela',
                          fontSize: 14.0)),
                  Text(name,
                      style: TextStyle(
                          color: Color(0xFF575E67),
                          fontFamily: 'Varela',
                          fontSize: 14.0)),
                  Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Container(color: Color(0xFFEBEBEB), height: 1.0)),
                  Padding(
                      padding: EdgeInsets.only(left: 5.0, right: 5.0),
                      child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            if (!added) ...[
                              Icon(Icons.shopping_basket,
                                  color: Color(0xFFD17E50), size: 12.0),
                              Text('Add to cart',
                                  style: TextStyle(
                                      fontFamily: 'Varela',
                                      color: Color(0xFFD17E50),
                                      fontSize: 12.0))
                            ],
                            if (added) ...[
                              Icon(Icons.remove_circle_outline,
                                  color: Color(0xFFD17E50), size: 12.0),
                              Text('3',
                                  style: TextStyle(
                                      fontFamily: 'Varela',
                                      color: Color(0xFFD17E50),
                                      fontWeight: FontWeight.bold,
                                      fontSize: 12.0)),
                              Icon(Icons.add_circle_outline,
                                  color: Color(0xFFD17E50), size: 12.0),
                            ]
                          ]))
                ]))));
  }
}
