import 'package:flutter/material.dart';
import 'package:blogapp/screens/product_detail.dart';

import '../constant.dart';

class HardDrinks extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFFFCFAF8),
      body: ListView(
        children: <Widget>[
          SizedBox(height: 15.0),
          Container(
              padding: EdgeInsets.only(right: 15.0),
              width: MediaQuery.of(context).size.width - 30.0,
              height: MediaQuery.of(context).size.height - 50.0,
              child: GridView.count(
                crossAxisCount: 2,
                primary: false,
                crossAxisSpacing: 10.0,
                mainAxisSpacing: 15.0,
                childAspectRatio: 0.8,
                children: <Widget>[
                  _buildCard(
                      '100 años 700 ml',
                      '\$140.00',
                      'imgs/HardDrink/100anosreposado.png',
                      false,
                      false,
                      "Detalle 100 años",
                      context),
                  _buildCard(
                      '400 Conejo',
                      '\$435.00',
                      'imgs/HardDrink/400conejos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      '1800 Cristalino',
                      '\$635.00',
                      'imgs/HardDrink/1800cristalino.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Absinth',
                      '\$555.00',
                      'imgs/HardDrink/Absinth.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Absolut Azul',
                      '\$259.00',
                      'imgs/HardDrink/AbsolutAzul.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Absolut Mandarina',
                      '\$259.00',
                      'imgs/HardDrink/AbsolutMandrin.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Alacrán Jóven ',
                      '\$639.00',
                      'imgs/HardDrink/AlacranJoven.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Alipús San Juan del Río',
                      '\$717.00',
                      'imgs/HardDrink/AlipusSanJuandelRio.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Appleton Estate',
                      '\$250.00',
                      'imgs/HardDrink/AppletonEstate.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Appleton Special',
                      '\$635.00',
                      'imgs/HardDrink/AppletonSpecial.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Azteca de Oro',
                      '\$150.00',
                      'imgs/HardDrink/AztecadeOro.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Bacardí Blanco',
                      '\$165.00',
                      'imgs/HardDrink/BacardiBlanco.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Bacardí Blanco 980 ml',
                      '\$210.00',
                      'imgs/HardDrink/BacardiBlanco980ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Bacardí Blanco 1750',
                      '\$310.00',
                      'imgs/HardDrink/BacardiBlanco1750.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Bacardi Solera',
                      '\$220.00',
                      'imgs/HardDrink/BacardiSolera.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Baileys Original',
                      '\$315.00',
                      'imgs/HardDrink/BaileysOriginal.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Beefeater',
                      '\$412.00',
                      'imgs/HardDrink/Beefeater.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Beringer White Zinfandel',
                      '\$201.00',
                      'imgs/HardDrink/BeringerWhiteZinfandel.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Black & White',
                      '\$200.00',
                      'imgs/HardDrink/BlackWhite.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard('Bombay', '\$475.00', 'imgs/HardDrink/Bombay.png',
                      false, false, "Detalle producto", context),
                  _buildCard('Bruxo', '\$515.00', 'imgs/HardDrink/Bruxo.png',
                      false, false, "Detalle producto", context),
                  _buildCard(
                      'Buchanans 12 años',
                      '\$780.00',
                      'imgs/HardDrink/Buchanans12anos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Buchanans 18 años',
                      '\$780.00',
                      'imgs/HardDrink/Buchanans18anos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Buchanans Master',
                      '\$895.00',
                      'imgs/HardDrink/BuchanansMaster.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Bulldog',
                      '\$550.00',
                      'imgs/HardDrink/Bulldog.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Captain Morgan Spiced 750 ml',
                      '\$149.00',
                      'imgs/HardDrink/CaptainMorganSpiced750ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Cardenal de Mendoza',
                      '\$1063.00',
                      'imgs/HardDrink/Cardenaldeendoza.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Cazadores Reposado',
                      '\$230.00',
                      'imgs/HardDrink/CazadoresReposado.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Centenario Plata 700 ml',
                      '\$305.00',
                      'imgs/HardDrink/CentenarioPlata700ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Centenario Plata 950 ml',
                      '\$317.00',
                      'imgs/HardDrink/CentenarioPlata950ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Centenario Reposado',
                      '\$255.00',
                      'imgs/HardDrink/centenarioreposado.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Chilensis Reserva',
                      '\$180.00',
                      'imgs/HardDrink/ChilensisReserva.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Chivas Regal 12 años',
                      '\$695.00',
                      'imgs/HardDrink/ChivasRegal12anos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Courvoisier V.S.',
                      '\$625.00',
                      'imgs/HardDrink/COURVOISIERVS.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Cune de Rioja Semidulce',
                      '\$200.00',
                      'imgs/HardDrink/CuneRiojaSemidulce.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Don julio 70',
                      '\$570.00',
                      'imgs/HardDrink/Donjulio70.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Don Julio 70 Añejo Cristalino',
                      '\$835.00',
                      'imgs/HardDrink/DonJulioReposado.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Don Pedro',
                      '\$160.00',
                      'imgs/HardDrink/DonPedro.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'El Jimador reposado',
                      '\$195.00',
                      'imgs/HardDrink/ElJimadorreposado.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Finca las Moras Malbec',
                      '\$142.00',
                      'imgs/HardDrink/FincalasMorasMalbec.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Frangelico',
                      '\$350.00',
                      'imgs/HardDrink/Frangelico.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Fundador',
                      '\$185.00',
                      'imgs/HardDrink/Fundador.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Glenfiddich 12 años',
                      '\$915.00',
                      'imgs/HardDrink/Glenfiddich12anos.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Grey Goose',
                      '\$660.00',
                      'imgs/HardDrink/GreyGoose.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Havana Club 750 ml',
                      '\$442.00',
                      'imgs/HardDrink/HavanaClub750ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Hendricks',
                      '\$750.00',
                      'imgs/HardDrink/Hendricks.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Hennessy V.S.O.P',
                      '\$1080.00',
                      'imgs/HardDrink/HennessyVSOP.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Herradura Reposado 700',
                      '\$549.00',
                      'imgs/HardDrink/HerraduraReposado700.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Hornitos Reposado 700',
                      '\$275.00',
                      'imgs/HardDrink/HornitosReposado700.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Hpnotiq',
                      '\$650.00',
                      'imgs/HardDrink/Hpnotiq.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Jack Daniels',
                      '\$415.00',
                      'imgs/HardDrink/JackDaniels.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Jagermeifter',
                      '\$320.00',
                      'imgs/HardDrink/Jagermeifter.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Jameson',
                      '\$371.00',
                      'imgs/HardDrink/Jameson.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard('J B', '\$240.00', 'imgs/HardDrink/JB.png', false,
                      false, "Detalle producto", context),
                  _buildCard(
                      'Johnnie Walker Etiqueta Negra',
                      '\$830.00',
                      'imgs/HardDrink/JohnnieWalkerEtiquetaNegra.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Johnnie Walker Etiqueta Roja',
                      '\$325.00',
                      'imgs/HardDrink/JohnnieWalkerEtiquetaRoja.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Jose Cuervo Especial',
                      '\$205.00',
                      'imgs/HardDrink/JoseCuervoEspecial.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Jose Cuervo tradicional',
                      '\$330.00',
                      'imgs/HardDrink/JoseCuervotradicional.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Kahlua Licor de Cafe',
                      '\$166.00',
                      'imgs/HardDrink/KahluaLicordeCafe.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Karat 1 lt',
                      '\$130.00',
                      'imgs/HardDrink/Karat1lt.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Kraken Black Spiced',
                      '\$165.00',
                      'imgs/HardDrink/KrakenBlackSpiced.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'L.A. Cetto Cabernet Sauvignon',
                      '\$136.00',
                      'imgs/HardDrink/LACetto.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'L.A. Cetto Blanc Zinfandel',
                      '\$131.00',
                      'imgs/HardDrink/LACettoBlancdeZinfandel.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Licor 43',
                      '\$430.00',
                      'imgs/HardDrink/Licor43.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Macallan Doble Cask',
                      '\$1260.00',
                      'imgs/HardDrink/MacallanDobleCask.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Maestro Dobel',
                      '\$650.00',
                      'imgs/HardDrink/MaestroDobel.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard('Malibu', '\$187.00', 'imgs/HardDrink/Malibu.png',
                      false, false, "Detalle producto", context),
                  _buildCard(
                      'Martell V.S.',
                      '\$700.00',
                      'imgs/HardDrink/Martellvs.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Martell V.S.O.P',
                      '\$949.00',
                      'imgs/HardDrink/MartellVSOP.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Matusalem Clasico',
                      '\$224.00',
                      'imgs/HardDrink/MatusalemClasico.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Matusalem Platino',
                      '\$190.00',
                      'imgs/HardDrink/MatusalemPlatino.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Mezcal Union Uno',
                      '\$N/A.00',
                      'imgs/HardDrink/MezcalUnionUno.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard('Midori', '\$405.00', 'imgs/HardDrink/Midori.png',
                      false, false, "Detalle producto", context),
                  _buildCard(
                      'Moet Chandon Brut',
                      '\$1050.00',
                      'imgs/HardDrink/MoetChandonBrut.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Moet Chandon Ice Imperial',
                      '\$1655.00',
                      'imgs/HardDrink/MoetChandonIceImperial.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Moet Chandon Rose',
                      '\$1295.00',
                      'imgs/HardDrink/MoetChandonRose.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Monte Xanic Merlot',
                      '\$545.00',
                      'imgs/HardDrink/MonteXanicMerlot.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard('Nuvo', '\$770.00', 'imgs/HardDrink/Nuvo.png',
                      false, false, "Detalle producto", context),
                  _buildCard(
                      'Oso Negro Ginebra',
                      '\$120.00',
                      'imgs/HardDrink/OsoNegroGinebra.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Oso Ngero 1 lt',
                      '\$90.00',
                      'imgs/HardDrink/OsoNgero1lt.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Passport Scotch',
                      '\$160.00',
                      'imgs/HardDrink/PassportScotch.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Remy Martin 1738',
                      '\$1420.00',
                      'imgs/HardDrink/RemyMartin1738.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Remy Martin V.S.O.P.',
                      '\$1100.00',
                      'imgs/HardDrink/RemyMartinVSOP.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Riunite Lambrusco',
                      '\$140.00',
                      'imgs/HardDrink/RiuniteLambrusco.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Riunite Prosecco',
                      '\$280.00',
                      'imgs/HardDrink/RiuniteProsecco.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard('Sauza', '\$229.00', 'imgs/HardDrink/Sauza.png',
                      false, false, "Detalle producto", context),
                  _buildCard(
                      'Skyy Vodka',
                      '\$165.00',
                      'imgs/HardDrink/SkyyVodka.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Smirnoff 750 ml',
                      '\$185.00',
                      'imgs/HardDrink/Smirnoff750ml.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Smirnoff Tamarindo',
                      '\$200.00',
                      'imgs/HardDrink/SmirnoffTamarindo.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Stolichnaya',
                      '\$265.00',
                      'imgs/HardDrink/Stolichnaya.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Tanqueray',
                      '\$455.00',
                      'imgs/HardDrink/Tanqueray.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Terry Centenario',
                      '\$280.00',
                      'imgs/HardDrink/TerryCentenario.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Torres 10',
                      '\$290.00',
                      'imgs/HardDrink/Torres10.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Torres 15',
                      '\$510.00',
                      'imgs/HardDrink/Torres15.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Torres 20',
                      '\$875.00',
                      'imgs/HardDrink/Torres20.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Wyborowa',
                      '\$139.00',
                      'imgs/HardDrink/Wyborowa.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'XA DOMECQ',
                      '\$120.00',
                      'imgs/HardDrink/XADOMECQ.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                  _buildCard(
                      'Zacapa 23',
                      '\$1100.00',
                      'imgs/HardDrink/Zacapa23.png',
                      false,
                      false,
                      "Detalle producto",
                      context),
                ],
              )),
          SizedBox(height: 15.0)
        ],
      ),
    );
  }

  Widget _buildCard(String name, String price, String imgPath, bool added,
      bool isFavorite, String detalle, context) {
    return Padding(
        padding: EdgeInsets.only(top: 5.0, bottom: 5.0, left: 5.0, right: 5.0),
        child: InkWell(
            onTap: () {
              Navigator.of(context).push(MaterialPageRoute(
                  builder: (context) => ProductDetail(
                        assetPath: imgPath,
                        cookieprice: price,
                        cookiename: name,
                        detalle: detalle,
                      )));
            },
            child: Container(
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15.0),
                    boxShadow: [
                      BoxShadow(
                          color: Colors.grey.withOpacity(0.2),
                          spreadRadius: 3.0,
                          blurRadius: 5.0)
                    ],
                    color: Colors.white),
                child: Column(children: [
                  Padding(
                      padding: EdgeInsets.all(5.0),
                      child: Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            isFavorite
                                ? Icon(Icons.favorite, color: Color(0xFFEF7532))
                                : Icon(Icons.favorite_border,
                                    color: Color(0xFFEF7532))
                          ])),
                  Hero(
                      tag: imgPath,
                      child: Container(
                          height: 110,
                          width: 110,
                          decoration: BoxDecoration(
                              image: DecorationImage(
                                  image: AssetImage(imgPath),
                                  fit: BoxFit.contain)))),
                  SizedBox(height: 7.0),
                  Text(price,
                      style: TextStyle(
                          color: PRYMARY_COLOR,
                          fontFamily: 'Varela',
                          fontSize: 14.0)),
                  Text(name,
                      style: TextStyle(
                          color: Color(0xFF575E67),
                          fontFamily: 'Varela',
                          fontSize: 14.0)),
                  Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Container(color: Color(0xFFEBEBEB), height: 1.0)),
                  Padding(
                      padding: EdgeInsets.only(left: 5.0, right: 5.0),
                      child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            if (!added) ...[
                              Icon(Icons.shopping_basket,
                                  color: Color(0xFFD17E50), size: 12.0),
                              Text('Add to cart',
                                  style: TextStyle(
                                      fontFamily: 'Varela',
                                      color: Color(0xFFD17E50),
                                      fontSize: 12.0))
                            ],
                            if (added) ...[
                              Icon(Icons.remove_circle_outline,
                                  color: Color(0xFFD17E50), size: 12.0),
                              Text('3',
                                  style: TextStyle(
                                      fontFamily: 'Varela',
                                      color: Color(0xFFD17E50),
                                      fontWeight: FontWeight.bold,
                                      fontSize: 12.0)),
                              Icon(Icons.add_circle_outline,
                                  color: Color(0xFFD17E50), size: 12.0),
                            ]
                          ]))
                ]))));
  }
}
