import 'package:flutter/material.dart';
import 'package:blogapp/screens/product_detail.dart';

import '../constant.dart';

class PistosMix extends StatelessWidget {
  var pistoxmixarr = [
    {
      {
        'Alfa Romeo',
        '95',
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Aston Martin',
        '129',
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      },
      {
        'Bentley Mango o Tamarindo',
        '109',
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
      },
      {
        'Bugatti',
        '85',
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Cadillac',
        '109',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Citroen',
        '85',
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Corvette',
        '119',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Ferrari',
        '109',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Hennessey',
        '129',
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      },
      {
        'Lamborghini',
        '99',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Lexus',
        '129',
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      },
      {
        'Likan',
        '129',
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      },
      {
        'Maserati',
        '99',
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      },
      {
        'Mastretta',
        '139',
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
      },
      {
        'Mclaren',
        '109',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
      },
      {
        'MG',
        '109',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Nos F1',
        '139',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Rolls Royce',
        '119',
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Saleen ',
        '119',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
      {
        'Porsche',
        '109',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
      },
      {
        'Venom',
        '129',
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      },
      {
        'Viper',
        '109',
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      },
    }
  ];
  var cervesas = [
    'Barrilito',
    'Blanc',
    'Bocanegra',
    'Bohemia Clara',
    'Bohemia Clásica',
    'Bohemia Obscura',
    'Bohemina Weizen ',
    'Brooklyn',
    'Bud Light',
    'Budweiser',
    'Carta Blanca',
    'Corona',
    'Corona l',
    'Cucapa',
    'Goose Island',
    'Gran Modelo',
    'Grimbergen',
    'Heineken',
    'Hoegaarden',
    'Indio ',
    'Jabalí',
    'Lagunitas Ipa',
    'León',
    'Michelob Ultra',
    'Modelo Ambar ',
    'Modelo Especial',
    'Modelo Trigo',
    'Montejo',
    'Negra Modelo',
    'Noche Buena ',
    'Pacifico',
    'Pacifico l',
    'Quilmes',
    'Sol',
    'Stella Artois',
    'Superior',
    'Tecate Ambar',
    'Tecate Ambar ',
    'Tecate Light',
    'Tecate Roja',
    'Tempus',
    'Tuborg',
    'Victoria',
    'XX Ambar',
    'xx Lager',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFFFCFAF8),
      body: ListView(
        children: <Widget>[
          SizedBox(height: 15.0),
          Container(
              padding: EdgeInsets.only(right: 15.0),
              width: MediaQuery.of(context).size.width - 30.0,
              height: MediaQuery.of(context).size.height - 50.0,
              child: GridView.count(
                crossAxisCount: 2,
                primary: false,
                crossAxisSpacing: 10.0,
                mainAxisSpacing: 15.0,
                childAspectRatio: 0.8,
                children: <Widget>[
                  _buildCard(
                      'Alfa romeo',
                      '\$95.00',
                      'imgs/PistosMix/Alfaromeo.png',
                      false,
                      false,
                      "Michelada tradicional sal, limón y  escarchado",
                      context),
                  _buildCard(
                      'Aston Martin',
                      '\$129.00',
                      'imgs/PistosMix/astonmartin.png',
                      false,
                      false,
                      "Michelada sabor Bluberry con Red Bull",
                      context),
                  _buildCard(
                      'Bentley',
                      '\$109.00',
                      'imgs/PistosMix/Bentley.png',
                      false,
                      false,
                      "Cerveza sabor a mango con nieve del mismo sabor",
                      context),
                  _buildCard(
                      'Bugatti',
                      '\$85.00',
                      'imgs/PistosMix/Bugatti.png',
                      false,
                      false,
                      "Sangría preparada con limón y sal ",
                      context),
                  _buildCard(
                      'Cadillac',
                      '\$109.00',
                      'imgs/PistosMix/Cadillac.png',
                      false,
                      false,
                      "Chabelita cerveza mezclada con refresco rojo, sal Y limón",
                      context),
                  _buildCard(
                      'Citroen',
                      '\$85.00',
                      'imgs/PistosMix/Citroen.png',
                      false,
                      false,
                      "Tehuacan preparado con limón y sal",
                      context),
                  _buildCard(
                      'Corvette',
                      '\$119.00',
                      'imgs/PistosMix/Corvette.png',
                      false,
                      false,
                      "Cerveza con sidra Strongbow gold sabor a frambuesa",
                      context),
                  _buildCard(
                      'Ferrari',
                      '\$109.00',
                      'imgs/PistosMix/Ferrari.png',
                      false,
                      false,
                      "Mezcla de sabor cerveza y chamoy",
                      context),
                  _buildCard(
                      'Hennessey',
                      '\$129.00',
                      'imgs/PistosMix/Hennessey.png',
                      false,
                      false,
                      "Michelada sabor frutos rojos con Red Bull",
                      context),
                  _buildCard(
                      'Lamborghinni',
                      '\$99.00',
                      'imgs/PistosMix/Lamborghinni.png',
                      false,
                      false,
                      "Michelada tradicional sal, limón y  escarchado",
                      context),
                  _buildCard(
                      'Lexus',
                      '\$129.00',
                      'imgs/PistosMix/Lexus.png',
                      false,
                      false,
                      "Michelada sabor manzana verde con Red Bull",
                      context),
                  _buildCard(
                      'Likan',
                      '\$129.00',
                      'imgs/PistosMix/Likan.png',
                      false,
                      false,
                      "Michelada sabor maracuya-chamoy verde con Red Bull",
                      context),
                  _buildCard(
                      'Masserati',
                      '\$99.00',
                      'imgs/PistosMix/Masserati.png',
                      false,
                      false,
                      "Michelada Cubana, salsa inglesa, salsa Maggy, salsa Valentina, salsa Tabasco, limón y sal",
                      context),
                  _buildCard(
                      'Mastretta',
                      '\$139.00',
                      'imgs/PistosMix/Mastretta.png',
                      false,
                      false,
                      "Michelada sabor pepino-morita y una onza de Mezcal ",
                      context),
                  _buildCard(
                      'Mclaren',
                      '\$109.00',
                      'imgs/PistosMix/Mclaren.png',
                      false,
                      false,
                      "Clamachela, cerveza con clamato natural",
                      context),
                  _buildCard('Mg', '\$109.00', 'imgs/PistosMix/Mg.png', false,
                      false, "Gomichela, mezcla de chamoy y gomitas ", context),
                  _buildCard(
                      'NosF1',
                      '\$139.00',
                      'imgs/PistosMix/NosF1.png',
                      false,
                      false,
                      "Cerveza sabor a uva y jugo de litchi",
                      context),
                  _buildCard(
                      'Porshe',
                      '\$109.00',
                      'imgs/PistosMix/porshe.png',
                      false,
                      false,
                      "Cerveza con sabores, fresa, coco, maracuya, piña, uva, durazno y chamoy",
                      context),
                  _buildCard(
                      'RollRoyce',
                      '\$119.00',
                      'imgs/PistosMix/RollRoyce.png',
                      false,
                      false,
                      "Calimocho, Vino tinto con limón, sal y Coca cola",
                      context),
                  _buildCard(
                      'Saleen',
                      '\$119.00',
                      'imgs/PistosMix/Saleen.png',
                      false,
                      false,
                      "Cerveza con Skyy Blue y sabor a mandarina",
                      context),
                  _buildCard(
                      'Venom',
                      '\$129.00',
                      'imgs/PistosMix/Venom.png',
                      false,
                      false,
                      "Michelada sabor piña colada con Red Bull",
                      context),
                  _buildCard(
                      'Viper',
                      '\$109.00',
                      'imgs/PistosMix/Viper.png',
                      false,
                      false,
                      "Cerveza con sabor a fresa- kiwi acompañada de bing picosito",
                      context),
                ],
              )),
          SizedBox(height: 15.0)
        ],
      ),
    );
  }

  Widget _buildCard(String name, String price, String imgPath, bool added,
      bool isFavorite, String detalle, context) {
    return Padding(
        padding: EdgeInsets.only(top: 5.0, bottom: 5.0, left: 5.0, right: 5.0),
        child: InkWell(
            onTap: () {
              Navigator.of(context).push(MaterialPageRoute(
                  builder: (context) => ProductDetail(
                        assetPath: imgPath,
                        cookieprice: price,
                        cookiename: name,
                        detalle: detalle,
                      )));
            },
            child: Container(
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15.0),
                    boxShadow: [
                      BoxShadow(
                          color: Colors.grey.withOpacity(0.2),
                          spreadRadius: 3.0,
                          blurRadius: 5.0)
                    ],
                    color: Colors.white),
                child: Column(children: [
                  Padding(
                      padding: EdgeInsets.all(5.0),
                      child: Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            isFavorite
                                ? Icon(Icons.favorite, color: Color(0xFFEF7532))
                                : Icon(Icons.favorite_border,
                                    color: Color(0xFFEF7532))
                          ])),
                  Hero(
                      tag: imgPath,
                      child: Container(
                          height: 110,
                          width: 110,
                          decoration: BoxDecoration(
                              image: DecorationImage(
                                  image: AssetImage(imgPath),
                                  fit: BoxFit.contain)))),
                  SizedBox(height: 7.0),
                  Text(price,
                      style: TextStyle(
                          color: PRYMARY_COLOR,
                          fontFamily: 'Varela',
                          fontSize: 14.0)),
                  Text(name,
                      style: TextStyle(
                          color: Color(0xFF575E67),
                          fontFamily: 'Varela',
                          fontSize: 14.0)),
                  Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Container(color: Color(0xFFEBEBEB), height: 1.0)),
                  Padding(
                      padding: EdgeInsets.only(left: 5.0, right: 5.0),
                      child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            if (!added) ...[
                              Icon(Icons.shopping_basket,
                                  color: Color(0xFFD17E50), size: 12.0),
                              Text('Add to cart',
                                  style: TextStyle(
                                      fontFamily: 'Varela',
                                      color: Color(0xFFD17E50),
                                      fontSize: 12.0))
                            ],
                            if (added) ...[
                              Icon(Icons.remove_circle_outline,
                                  color: Color(0xFFD17E50), size: 12.0),
                              Text('3',
                                  style: TextStyle(
                                      fontFamily: 'Varela',
                                      color: Color(0xFFD17E50),
                                      fontWeight: FontWeight.bold,
                                      fontSize: 12.0)),
                              Icon(Icons.add_circle_outline,
                                  color: Color(0xFFD17E50), size: 12.0),
                            ]
                          ]))
                ]))));
  }
}
